agent_name: fb

lr: 3e-4
batch_size: 1024
discrete: ${env.discrete}

# MISC
discount: 0.98  # Discount factor. 0.99 - for maze, 0.98 others
tau: 0.01  # Target network update rate.
clip_by_global_norm: True

# Dataset hyperparameters.
dataset_class: GCDataset  # Dataset class name.
value_p_curgoal: 0.0  # Probability of using the current state as the value goal.
value_p_trajgoal: 1.0  # Probability of using a future state in the same trajectory as the value goal.
value_p_randomgoal: 0.0  # Probability of using a random state as the value goal.
value_geom_sample: True  # Whether to use geometric sampling for future value goals.
actor_p_curgoal: 0.0  # Probability of using the current state as the actor goal.
actor_p_trajgoal: 0.0  # Probability of using a future state in the same trajectory as the actor goal.
actor_p_randomgoal: 1.0  # Probability of using a random state as the actor goal.
actor_geom_sample: False  # Whether to use geometric sampling for future actor goals.
gc_negative: True  # Whether to use '0 if s : :  g else -1' (True) or '1 if s : :  g else 0' (False) as reward.
p_aug: 0.0  # Probability of applying image augmentation.
frame_stack: null  # Number of frames to stack.
