# Most of hyperparams from zero-shot rl from high-quality data
# https://arxiv.org/pdf/2309.15178
agent_name: fb

lr: 1e-4
batch_size: 1024
discrete: ${env.discrete}

# FB Specific
z_dim: 50 # 100 for maze env, 50 for others
fb_forward_hidden_dims: [1024, 1024]  # Value network hidden dimensions.
fb_layer_norm_only_first: True # use tanh + layernorm in first layer
fb_forward_layer_norm: False  # Whether to use layer normalization.
fb_preprocessor_layer_norm: False
fb_forward_preprocessor_hidden_dims: [512, 512]
fb_backward_hidden_dims: [256, 256, 256]  # Value network hidden dimensions.
fb_backward_layer_norm: False  # Whether to use layer normalization.
z_mix_ratio: 0.5

# Actor
actor_hidden_dims: [1024, 1024]  # Actor network hidden dimensions.
actor_layer_norm: False  # Whether to use layer normalization for the actor.
boltzmann: False # TODO: add later maybe?

# MISC
discount: 0.99  # Discount factor. 0.99 - for maze, 0.98 others
tau: 0.005  # Target network update rate.
tanh_squash: True  # Whether to squash actions with tanh.
state_dependent_std: False  # Whether to use state-dependent standard deviations for actor.
actor_fc_scale: 0.01  # Final layer initialization scale for actor.
const_std: True

# Dataset hyperparameters.
dataset_class: GCDataset  # Dataset class name.
value_p_curgoal: 0.0  # Probability of using the current state as the value goal.
value_p_trajgoal: 0.5  # Probability of using a future state in the same trajectory as the value goal.
value_p_randomgoal: 0.5  # Probability of using a random state as the value goal.
value_geom_sample: True  # Whether to use geometric sampling for future value goals.
actor_p_curgoal: 0.0  # Probability of using the current state as the actor goal.
actor_p_trajgoal: 0.0  # Probability of using a future state in the same trajectory as the actor goal.
actor_p_randomgoal: 1.0  # Probability of using a random state as the actor goal.
actor_geom_sample: False  # Whether to use geometric sampling for future actor goals.
gc_negative: True  # Whether to use '0 if s : :  g else -1' (True) or '1 if s : :  g else 0' (False) as reward.
p_aug: 0.0  # Probability of applying image augmentation.
frame_stack: null  # Number of frames to stack.
